In [90]:
import pandas as pd
import numpy as np
import re
import string
import pickle

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score, hamming_loss, f1_score

In [91]:
messages = pd.read_csv('../dataset/disaster_messages.csv')

categories = pd.read_csv('../dataset/disaster_categories.csv')

In [92]:
messages.head()

,id,message,original,genre
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct

In [93]:
categories.head()

   id                                         categories
0   2  related-1;request-0;offer-0;aid_related-0;medi...
1   7  related-1;request-0;offer-0;aid_related-1;medi...
2   8  related-1;request-0;offer-0;aid_related-0;medi...
3   9  related-1;request-1;offer-0;aid_related-1;medi...
4  12  related-1;request-0;offer-0;aid_related-0;medi...

In [94]:
df = messages.merge(
    categories,
    on="id"
)

In [95]:
df.head()

,id,message,original,genre,categories
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct,related-1;request-0;offer-0;aid_related-0;medi...
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct,related-1;request-0;offer-0;aid_related-1;medi...
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct,related-1;request-0;offer-0;aid_related-0;medi...
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct,related-1;request-1;offer-0;aid_related-1;medi...
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct,related-1;request-0;offer-0;aid_related-0;medi...

In [96]:
categories_column = df["categories"]

In [97]:
category_names = categories_column.iloc[0].split(";")

In [98]:
category_names

['related-1',
 'request-0',
 'offer-0',
 'aid_related-0',
 'medical_help-0',
 'medical_products-0',
 'search_and_rescue-0',
 'security-0',
 'military-0',
 'child_alone-0',
 'water-0',
 'food-0',
 'shelter-0',
 'clothing-0',
 'money-0',
 'missing_people-0',
 'refugees-0',
 'death-0',
 'other_aid-0',
 'infrastructure_related-0',
 'transport-0',
 'buildings-0',
 'electricity-0',
 'tools-0',
 'hospitals-0',
 'shops-0',
 'aid_centers-0',
 'other_infrastructure-0',
 'weather_related-0',
 'floods-0',
 'storm-0',
 'fire-0',
 'earthquake-0',
 'cold-0',
 'other_weather-0',
 'direct_report-0']

In [99]:
category_colnames = [
    row.split("-")[0]
    for row in category_names
]

In [100]:
categories_column.head()

0    related-1;request-0;offer-0;aid_related-0;medi...
1    related-1;request-0;offer-0;aid_related-1;medi...
2    related-1;request-0;offer-0;aid_related-0;medi...
3    related-1;request-1;offer-0;aid_related-1;medi...
4    related-1;request-0;offer-0;aid_related-0;medi...
Name: categories, dtype: str

In [101]:
categories_expanded = categories_column.str.split(
    ";",
    expand=True
)

In [102]:
for column in categories_expanded:

    categories_expanded[column] = categories_expanded[column].apply(
        lambda x: int(x.split("-")[1])
    )

    categories_expanded[column] = categories_expanded[column].replace(2, 1)

In [103]:
categories_expanded.columns = category_colnames

In [104]:
df = df.drop(columns=["categories"])

In [105]:
df = pd.concat(
    [df, categories_expanded],
    axis=1
)

df = df.drop_duplicates()

df = df.dropna(
    subset=["message"]
)

df.head()

,id,message,original,genre,related,request,offer,aid_related,medical_help,medical_products,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct,1,0,0,1,0,0,...,0,0,1,0,1,0,0,0,0,0
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct,1,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [106]:
df.head()

,id,message,original,genre,related,request,offer,aid_related,medical_help,medical_products,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct,1,0,0,1,0,0,...,0,0,1,0,1,0,0,0,0,0
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct,1,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [107]:
def clean_text(text):

    text = text.lower()

    text = re.sub(r"http\S+", "", text)

    text = re.sub(r"@\w+", "", text)

    text = re.sub(r"#", "", text)

    text = text.translate(
        str.maketrans("", "", string.punctuation)
    )

    text = text.strip()

    return text

In [108]:
print(df.shape)
print(df["message"].isnull().sum())

(26215, 40)
0

In [109]:
df["clean_message"] = df["message"].apply(
    clean_text
)

In [110]:
valid_columns = []

for column in category_colnames:

    unique_values = df[column].nunique()

    positive_count = df[column].sum()

    if unique_values > 1 and positive_count > 100:

        valid_columns.append(column)

category_colnames = valid_columns

X = df["clean_message"]

y = df[category_colnames].astype(int)

In [111]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [112]:
tfidf = TfidfVectorizer(

    max_features=30000,

    ngram_range=(1,2),

    stop_words="english",

    sublinear_tf=True,

    min_df=2,

    max_df=0.90
)

In [113]:
X_train_tfidf = tfidf.fit_transform(
    X_train
)

X_test_tfidf = tfidf.transform(
    X_test
)

In [114]:
model = OneVsRestClassifier(

    LogisticRegression(
        max_iter=2000,
        class_weight="balanced",
        solver="liblinear",
    )

)

In [115]:
model.fit(
    X_train_tfidf,
    y_train.values
)

OneVsRestClassifier(estimator=LogisticRegression(class_weight='balanced',
                                                 max_iter=2000,
                                                 solver='liblinear'))

In [116]:
y_pred = model.predict(
    X_test_tfidf
)

In [117]:
print(
    classification_report(
        y_test.values,
        y_pred,
        target_names=category_colnames,
        zero_division=0
    )
)

                        precision    recall  f1-score   support

               related       0.91      0.81      0.86      3998
               request       0.61      0.72      0.66       891
                 offer       0.00      0.00      0.00        24
           aid_related       0.73      0.74      0.74      2164
          medical_help       0.40      0.64      0.49       435
      medical_products       0.32      0.57      0.41       279
     search_and_rescue       0.22      0.39      0.28       136
              security       0.10      0.15      0.12        96
              military       0.38      0.70      0.50       158
                 water       0.60      0.84      0.70       335
                  food       0.74      0.86      0.80       584
               shelter       0.57      0.78      0.65       468
              clothing       0.38      0.60      0.47        70
                 money       0.32      0.62      0.42       112
        missing_people       0.22      0.32      0.26        63
              refugees       0.32      0.61      0.42       170
                 death       0.47      0.70      0.56       247
             other_aid       0.33      0.54      0.41       692
infrastructure_related       0.23      0.48      0.31       336
             transport       0.27      0.44      0.33       235
             buildings       0.42      0.67      0.52       269
           electricity       0.46      0.57      0.51       115
                 tools       0.05      0.03      0.04        35
             hospitals       0.21      0.35      0.26        52
                 shops       0.04      0.04      0.04        25
           aid_centers       0.15      0.28      0.19        64
  other_infrastructure       0.18      0.40      0.25       225
       weather_related       0.75      0.79      0.77      1472
                floods       0.57      0.70      0.63       431
                 storm       0.61      0.82      0.70       479
                  fire       0.31      0.30      0.30        53
            earthquake       0.81      0.83      0.82       515
                  cold       0.42      0.58      0.49       104
         other_weather       0.25      0.48      0.33       267
         direct_report       0.54      0.67      0.60      1010

             micro avg       0.58      0.71      0.64     16609
             macro avg       0.40      0.54      0.45     16609
          weighted avg       0.64      0.71      0.67     16609
           samples avg       0.44      0.53      0.44     16609

In [118]:
hamming = hamming_loss(
    y_test,
    y_pred
)

micro_f1 = f1_score(
    y_test,
    y_pred,
    average="micro"
)

macro_f1 = f1_score(
    y_test,
    y_pred,
    average="macro"
)

weighted_f1 = f1_score(
    y_test,
    y_pred,
    average="weighted"
)

print("\nMODEL EVALUATION\n")

print(f"Hamming Loss: {hamming:.4f}")

print(f"Micro F1 Score: {micro_f1:.4f}")

print(f"Macro F1 Score: {macro_f1:.4f}")

print(f"Weighted F1 Score: {weighted_f1:.4f}")

MODEL EVALUATION

Hamming Loss: 0.0724
Micro F1 Score: 0.6406
Macro F1 Score: 0.4523
Weighted F1 Score: 0.6654

In [119]:
pickle.dump(
    model,
    open(
        "../server/artifacts/model.pkl",
        "wb"
    )
)

In [120]:
pickle.dump(
    tfidf,
    open(
        "../server/artifacts/vectorizer.pkl",
        "wb"
    )
)

In [121]:
pickle.dump(
    category_colnames,
    open(
        "../server/artifacts/label_columns.pkl",
        "wb"
    )
)

In [122]:
def get_priority(

    predicted_labels,
    message

):

    high_priority_labels = [

        "search_and_rescue",
        "medical_help",
        "death",
        "water",
        "food",
        "shelter"

    ]

    medium_priority_labels = [

        "floods",
        "storm",
        "earthquake",
        "fire",
        "buildings",
        "electricity",
        "transport"

    ]

    urgency_keywords = [

        "urgent",
        "immediately",
        "trapped",
        "dying",
        "injured",
        "collapsed",
        "starving",
        "critical",
        "help",
        "rescue"

    ]

    high_score = 0

    medium_score = 0

    for label in predicted_labels:

        if label in high_priority_labels:

            high_score += 2

        elif label in medium_priority_labels:

            medium_score += 1

    message = message.lower()

    urgency_score = 0

    for word in urgency_keywords:

        if word in message:

            urgency_score += 1

    total_score = (
        high_score +
        medium_score +
        urgency_score
    )

    if total_score >= 6:

        return "HIGH"

    elif total_score >= 3:

        return "MEDIUM"

    else:

        return "LOW"

In [123]:
sample_message = "Free fire game destroyed my career."

In [124]:
clean_sample = clean_text(
    sample_message
)

In [125]:
sample_vector = tfidf.transform(
    [clean_sample]
)

In [126]:
probabilities = model.predict_proba(
    sample_vector
)

threshold = 0.75

ignore_labels = [

    "related",
    "aid_related",
    "request"

]

display_ignore_labels = [

    "direct_report",
    "other_aid",
    "weather_related",
    "infrastructure_related",
    "other_weather",
    "other_infrastructure"

]

predicted_labels = []

for label, prob in zip(category_colnames, probabilities[0]):

    if prob >= threshold and label not in ignore_labels and label not in display_ignore_labels:
        predicted_labels.append(label)

In [127]:
priority = get_priority(

    predicted_labels,
    message,

)

In [128]:
print("\nPredicted Emergency Categories:\n")

for label in predicted_labels:

    print(f"- {label}")
    
print(f"\nAssigned Priority: {priority}")

Predicted Emergency Categories:

- buildings

Assigned Priority: LOW

In [129]:
test_cases = [

    "People are trapped inside the collapsed building and urgently need medical assistance and clean water",

    "There has been no electricity for three days and families are struggling without food supplies",

    "I am watching a movie at home while eating pizza during heavy rain outside",

    "Children in the camp are starving and require immediate food and medical support",

    "Roads are flooded and rescue teams cannot reach the village because bridges are damaged",

    "My internet is slow and I cannot play online games tonight",

    "Huge fire accident near the hospital and many people are injured",

    "Families lost their homes after the cyclone and need shelter immediately",

    "Heavy earthquake destroyed several buildings and rescue teams are required urgently",

    "Water supply has been completely cut off and people are suffering badly"
]

In [130]:
for index, message in enumerate(test_cases, start=1):

    clean_sample = clean_text(message)

    sample_vector = tfidf.transform(
        [clean_sample]
    )

    probabilities = model.predict_proba(
        sample_vector
    )

    threshold = 0.75

    ignore_labels = [

        "related",
        "aid_related",
        "request"

    ]

    display_ignore_labels = [

    "direct_report",
    "other_aid",
    "weather_related",
    "infrastructure_related",
    "other_weather",
    "other_infrastructure"

    ]
    

    predicted_labels = []

    for label, prob in zip(
        category_colnames,
        probabilities[0]
    ):

        
        if prob >= threshold and label not in ignore_labels and label not in display_ignore_labels:

            predicted_labels.append(label)
    
    if not predicted_labels:

        print("No disaster-related categories detected.")

    priority = get_priority(

        predicted_labels,
        message

    )

    print("\n====================================")

    print(f"\nTEST CASE {index}")

    print(f"\nMESSAGE:\n{message}")

    print("\nPREDICTED LABELS:\n")

    for label, prob in zip(
    category_colnames,
    probabilities[0]
):

        if label in predicted_labels:

            print(f"- {label}: {prob:.2f}")

    print(f"\nPRIORITY LEVEL: {priority}")

    print("\n====================================")

====================================

TEST CASE 1

MESSAGE:
People are trapped inside the collapsed building and urgently need medical assistance and clean water

PREDICTED LABELS:

- medical_help: 0.95
- medical_products: 0.81
- search_and_rescue: 0.82
- water: 0.94
- buildings: 0.93

PRIORITY LEVEL: HIGH

====================================

====================================

TEST CASE 2

MESSAGE:
There has been no electricity for three days and families are struggling without food supplies

PREDICTED LABELS:

- medical_products: 0.90
- food: 0.99
- electricity: 0.94

PRIORITY LEVEL: MEDIUM

====================================

====================================

TEST CASE 3

MESSAGE:
I am watching a movie at home while eating pizza during heavy rain outside

PREDICTED LABELS:

- storm: 0.96

PRIORITY LEVEL: LOW

====================================

====================================

TEST CASE 4

MESSAGE:
Children in the camp are starving and require immediate food and medical support

PREDICTED LABELS:

- medical_help: 0.96
- medical_products: 0.82
- food: 1.00

PRIORITY LEVEL: MEDIUM

====================================

====================================

TEST CASE 5

MESSAGE:
Roads are flooded and rescue teams cannot reach the village because bridges are damaged

PREDICTED LABELS:

- search_and_rescue: 0.99
- transport: 0.99
- buildings: 0.81
- floods: 0.90

PRIORITY LEVEL: HIGH

====================================
No disaster-related categories detected.

====================================

TEST CASE 6

MESSAGE:
My internet is slow and I cannot play online games tonight

PREDICTED LABELS:


PRIORITY LEVEL: LOW

====================================

====================================

TEST CASE 7

MESSAGE:
Huge fire accident near the hospital and many people are injured

PREDICTED LABELS:

- medical_help: 0.99
- death: 0.82
- hospitals: 0.92

PRIORITY LEVEL: MEDIUM

====================================

====================================

TEST CASE 8

MESSAGE:
Families lost their homes after the cyclone and need shelter immediately

PREDICTED LABELS:

- shelter: 1.00
- refugees: 0.77
- buildings: 0.93
- storm: 0.79

PRIORITY LEVEL: MEDIUM

====================================

====================================

TEST CASE 9

MESSAGE:
Heavy earthquake destroyed several buildings and rescue teams are required urgently

PREDICTED LABELS:

- search_and_rescue: 0.96
- buildings: 0.99
- earthquake: 0.98

PRIORITY LEVEL: HIGH

====================================

====================================

TEST CASE 10

MESSAGE:
Water supply has been completely cut off and people are suffering badly

PREDICTED LABELS:

- water: 0.96

PRIORITY LEVEL: LOW

====================================